### ISSUE TITLE
Conflict with ResevedItemSlots (HotbarPlus)

### ISSUE THREAD

**Issue by Paradox75831004** [LegaSource/CursedScraps#1]
https://thunderstore.io/c/lethal-company/p/FlipMods/HotbarPlus/

[LogOutput.log](https://github.com/LegaSource/CursedScraps/files/14861939/LogOutput.log)
 
018ea7ad-2867-80a5-9eb7-823727197b79 (code profile)

https://drive.google.com/file/d/1xv0TbMyIA-LiLcIVXXbeZ3bWjABqiCwd/view?usp=sharing (video test error)

Conflict with this mod, contact the creator of this mod and solve the problem, thanks in advance! (I like your mod)

https://discord.com/channels/1168655651455639582/1177039162428366848

**Comment by LegaSource** [comment]
Sorry, I didn't expect to receive messages via GitHub x) Thanks for your interest in my mod!
Do you know if the issue is still there? I had already made a correction to the method mentioned in the log
