### ISSUE TITLE
[Bug] Pills do not spawn at all

### ISSUE THREAD

**Issue by DSMister** [LegaSource/CursedScraps#19]
Hi! As of the latest update, I am completely unable to find any anti-curse pills at all. Even if I set the chance in the config to 100%, they will not appear at all. I even tried to only run that mod.

**Comment by LegaSource** [comment]
Hello, the pills have been disabled for now (since version 2.0.0)
I plan to modify how they work and will likely create a new model for them (possibly something like holy water)
Additionally, the 'EXPLORATION' curse and the hiding mechanic have also been disabled as I intend to improve them

**Comment by DSMister** [comment]
Ah! That actually explains everything! Thank you!
