### ISSUE TITLE
ERRANT and CAPTIVE Cursed Scraps cause continuous teleportation

### ISSUE THREAD

**Issue by Lcinit** [LegaSource/CursedScraps#2]
When there are ERRANT and CAPTIVE cursed items in the inventory, you can continuously try to discard the CAPTIVE item. This will have a continuous teleportation effect.Is this the original design or is there a problem?

**Comment by Lcinit** [comment]
2、When there is an ERRANT curse, dropping items on the ship will also trigger the teleportation effect。

**Comment by LegaSource** [comment]
These are cases I hadn't considered, I'll make a correction for my next update. Thanks for the feedback!
If the issue is too bothersome in the meantime, you can disable the effect in the configuration file

**Comment by Lcinit** [comment]
Thank you! I have modified the source code of TeleportPlayer to enable it to generate and use.
>        private static void TeleportPlayer(ref PlayerControllerB player)
>         {
>             string curseEffectHeld = GetCurseEffect(ref player.currentlyHeldObjectServer);
>             if ( curseEffectHeld != Constants.CAPTIVE && !player.isInHangarShipRoom)
>             {
>               .....
>             }
>         }

**Comment by LegaSource** [comment]
That's what I had in mind, yes. I'll test to see if the teleportation activates properly when picking up the CAPTIVE object, but it should be fine
I'll make the modification as soon as I have time before my next release. I've already started on the next curse, but I don't want to rush the work
