### ISSUE TITLE
[Enhancement] Hide curse in tooltip

### ISSUE THREAD

**Issue by ProjectBots** [LegaSource/CursedScraps#3]
Atm one can see what curse is on the item before it gets picked up.
I want to introduce some fun and hide this information :)

**Comment by LegaSource** [comment]
Do you want it to be permanent? I was thinking of a similar system, but one that only activates after a certain time and until a player picks up a new curse

**Comment by ProjectBots** [comment]
Permanent is perfect for me.

**Comment by LegaSource** [comment]
Alright, I'll add an option for that in the next curse update
