### ISSUE TITLE
Can't move when picking up a "Synchronization" item

### ISSUE THREAD

**Issue by 1111-glitch** [LegaSource/CursedScraps#4]
It doesn't mention anything about it on the modpage and I looked at the source code and it seems to be an intended effect I think? So if it is I think you should change the description to reflect that. If it's not intended I can happily provide a log file.

Great job on the mod by the way, really glad someone improved upon the strange objects mod. It had so much potential but nothing was really done with it.

**Comment by LegaSource** [comment]
That's intentional! I'll add some clarification on the page
It's to prevent the player from bringing the first part directly to the ship and doing the same with the second afterward
Thanks for your kind words! Have fun :)
