### ISSUE TITLE
[Enhancement] Feature parity with Strange Objects

### ISSUE THREAD

**Issue by 1111-glitch** [LegaSource/CursedScraps#5]
The only thing this mod is missing to be 1:1 on features with strange objects is the ability to edit the floats of the curse effect, like how strong the blurriness is and how much it increments with each additional curse picked up. I would really love if these features were added!

**Comment by Darkmega18** [comment]
Agree too.

**Comment by LegaSource** [comment]
I'll add more configs, but I don't want to make an effect more powerful based on how many times it's picked up
I want each curse to have 100% of its capabilities with a fixed price already set on the scrap
