### ISSUE TITLE
[Bug] Diminutive makes everyone fast

### ISSUE THREAD

**Issue by 1111-glitch** [LegaSource/CursedScraps#6]
I'm assuming it's doing this because instead of adding speed back to just the player who picked it up it adds it to everyone.

**Comment by LegaSource** [comment]
Do you have the 'abandonedcompanyassets' mod? I've been informed of a similar compatibility issue with that mod, so I need to look into it

**Comment by 1111-glitch** [comment]
I do not, here is my modlist.

[mods.txt](https://github.com/LegaSource/CursedScraps/files/15140267/mods.txt)

**Comment by LegaSource** [comment]
I think I've found the issue, and it turns out it wasn't related with abandonedcompanyassets. Let me know if the problem occurs again for you!
