### ISSUE TITLE
[enhancement] Cursed generation rarities

### ISSUE THREAD

**Issue by Darkmega18** [LegaSource/CursedScraps#7]
Basically add a config similar to what people make for a lethal level loader interior where theres a weight or chance for each map or for subsets of maps where you can set what percentage chance of items will go cursed.

For example in a map like egypt where one might like to have more supernatural activity entities, curses could occur there more if one wants to get heavily into tailoring their packs or experiences.

**Comment by LegaSource** [comment]
I'll change the global percentage config to make it configurable for each planet, and with a default value (similar to the weight config for each curse) for my next update

**Comment by VioletXe** [comment]
Nice, I was just about to comment for this. I'd LOVE it if this could be added, would really round out unique scrap experiences.
