### ISSUE TITLE
[enhancement/idea] "Cursed Artifacts"

### ISSUE THREAD

**Issue by Darkmega18** [LegaSource/CursedScraps#8]
Basically, make a sister mod with cross compat with this one (and maybe draw some inspiration from a mod like emergency dice) that adds a mechanic where specific special cursed items with even more powerful effects trigger from, similar to say a meltdown or picking up the painting in the scarlet devil mansion.

These items would very obviously have runes or effects on them that make them stand out, and getting greedy can get you rich or very dead.

**Comment by LegaSource** [comment]
The curses I add in this mod are already more or less dangerous, and the value of each one is configurable (I don't know if you've tried, but the 'Synchronization' curse is really difficult to play with)
However, I try to avoid adding effects that I find boring, like simply reducing the player's speed
So, I aim to find new unique and entertaining mechanics
If you have any ideas for curses that might interest me, I'd be happy to hear them, but I don't plan on making another mod dependent on this one for the moment
