### ISSUE TITLE
[Issue] about Diminutive

### ISSUE THREAD

**Issue by CoolLKKPS** [LegaSource/CursedScraps#9]
update soon

**Comment by CoolLKKPS** [comment]
u only need to have these mods:
BepInEx v5.4.2100 by BepInEx
CursedScraps v1.0.5 by Lega
HookGenPatcher v0.0.5 by Evaisa
LethalLib v0.15.1 by Evaisa
ToyboxBetaTest v0.6.4 by Toybox - LittleCompany Beta Version

**Comment by LegaSource** [comment]
I'm not sure if you have any specific conflicts, if you do, could you specify them for me?
I'm not familiar with the gameplay of LittleCompany, but if it's completely different from the curse, perhaps it's better to disable this effect?

**Comment by CoolLKKPS** [comment]
uh maybe u have to test that by ur own, bc little busy at this moment for me, and sure disable this effect should fix this conflict, not even fix the view de-sync

**Comment by CoolLKKPS** [comment]
@LegaSource uh well, will start test this issue today, just let u know

**Comment by CoolLKKPS** [comment]
and actually i have another issue about `Localization`, from other peoples report, the curse only happen if match the curse text not ids

**Comment by CoolLKKPS** [comment]
in recently update, i can't reproduce view de-sync issue now, but some curse won't automally removed, for example:
0. with littlecompany (toybox beta), after get that curse and use potion or raygun to get back to normal size
1. if player died by colliding with other players
2. the hoster decide quit to main menu and re-create a lobby
Result: curse won't removed even u are in normal size, u will instantly killed by colliding with other players

**Comment by CoolLKKPS** [comment]
and also littlecompany mod might know how tiny the player are, but they decide to change size from 0.2 to 0.6, and that's reasonable tbh
